### ISSUE TITLE
Mistral

### ISSUE THREAD

**Issue by fakerybakery** [sramshetty/ShortGPT#1]
Hi,
Thank you for releasing this implementation! Do you have any plans to add support for Mistral 7B?
Thanks!

**Comment by sramshetty** [comment]
No plans but I can definitely try to, will let you know how it goes -- hopefully this week!

**Comment by fakerybakery** [comment]
Thanks!

**Comment by sramshetty** [comment]
I attempted to add support for CausalLM models from HuggingFace which would include Mistral-7B on a separate [branch](https://github.com/sramshetty/ShortGPT/tree/hf-models) (probably need to do some testing or wait till people try it out themselves).

I ran over a subset of the pg19 val set to verify, and found that the same 9 layers were deemed least important (different order). You can check that out [here](https://github.com/sramshetty/ShortGPT/blob/hf-models/short_gpt/short_hf.ipynb).

Hopefully this is what you were looking!

**Comment by fakerybakery** [comment]
Cool! Thanks!
