### ISSUE TITLE
Provide an implemention on hf transformers

### ISSUE THREAD

**Issue by xpq-tech** [sramshetty/ShortGPT#4]
https://github.com/Brett-z/LayerRemoval
This repo provides an implementation for layer removal in the HuggingFace Transformers library

**Comment by sramshetty** [comment]
Thanks for sharing! Do you know if it handles removal the same or different to my HuggingFace removal [implementation](https://github.com/sramshetty/ShortGPT/blob/hf-models/short_gpt/short_hf.py#L37)?

**Comment by xpq-tech** [comment]
Yes! Your HuggingFace removal is almost the same as https://github.com/Brett-z/LayerRemoval, and it's more concise. Thanks for your contributions.
